import { nanoid } from 'nanoid';

// HEAD DATA
export const headData = {
  title: "Paulo Cuijia's Portfolio Website", // e.g: 'Name | Developer'
  lang: 'en', // e.g: en, es, fr, jp
  description:
    'This is a portfolio website to showcase my projects and provide more information about myself.', // e.g: Welcome to my website
};

// HERO DATA
export const heroData = {
  title: '',
  name: 'Paulo Cuijia',
  subtitle: " and I'm a Front-End Developer",
  cta: '',
};

// ABOUT DATA
export const aboutData = {
  img: 'DSC02090 copy2.JPG',
  paragraphOne:
    "I'm Paulo Cuijia and I'm bilingual, I speak english and portuguese both fluently.I live in Lisbon Portugal and I'm currently studying computer science at Universidade Europeia.I have over one year of experience in the front-end engineering world and thus I hav developed a wide range of skills such as HTML,CSS,Javascript,React&Redux,Material UI,Bootstrap,Sass,D3,jQuery",
  paragraphTwo:
    "I'am a very hard worker and I'm available 24/7.I'm always looking to improve myself and reach new heights,I'm very self motivated as i always aim to be the best version of myself.",
  paragraphThree:
    'Programming is my passion and has been my passion for as long as I can remember.I aim to making a lasting legacy through my work in software and leave a mark on my community and world just like my heroes Steve Jobs and Elon Musk',
  resume: '', // if no resume, the button will not show up
};

// PROJECTS DATA
export const projectsData = [
  {
    id: nanoid(),
    img: 'Profile App 2 (2).png',
    title: 'Profile App',
    info: 'Profile App is a react website that displays user information such their name,job,avatar photo and bit of personal information.',
    info2:
      'The App is completely interactive and responsive to all screen sizes.To interact with the app you click on the arrows and switch bewteen users.',
    url: '',
    repo: 'https://github.com/hotoniel79/Profile-App.git', // if no repo, the button will not show up
  },
  {
    id: nanoid(),
    img: 'Untitled (3).png',
    title: 'Piano App',
    info: 'Piano app is javascript built website designed to be a web page game.',
    info2:
      'Piano app is fully responsive and can interacted with by clicking on the piano keys as it returns musical notes.',
    url: '',
    repo: 'https://github.com/hotoniel79/Piano-app.git', // if no repo, the button will not show up
  },
  {
    id: nanoid(),
    img: 'Random quote machine 3 (2).png',
    title: 'Quote Machine',
    info: 'Quote Machine a react app that generates random quotes.',
    info2:
      'Quote Machine is fully responsive as well as interactive.Different quotes can be generated by clicking on the button and as the quotes change so does the background color.',
    url: '',
    repo: 'https://github.com/hotoniel79/Quote-Machince.git', // if no repo, the button will not show up
  },
];

// CONTACT DATA
export const contactData = {
  cta: '',
  btn: '',
  email: 'hotoniel79@icloud.com',
};

// FOOTER DATA
export const footerData = {
  networks: [
    {
      id: nanoid(),
      name: 'hotoniel79',
      url: 'https://github.com/hotoniel79',
    },
  ],
};

// Github start/fork buttons
export const githubButtons = {
  isEnabled: false, // set to false to disable the GitHub stars/fork buttons
};
